###
GET http://localhost:8080/public/deals/all

###
GET http://localhost:8080/public/deals/6

###
POST http://localhost:8080/deals
Authorization: Basic emma a
Content-Type: application/json

{
  "title": "withCredentials",
  "description": "bbb",
  "priceOld": 2,
  "priceNew": 1,
  "shopName": "shop",
  "promoCode": "ccc",
  "creatorId": 3,
  "imgUrl": "img"
}
